- hosts: all
  sudo: yes
  vars:
  roles:
    - { role: magnus919.epel, when: ansible_os_family == 'RedHat' }
    - base
    - { role: php55, when: ansible_os_family != "RedHat" }
    - { role: php55-centos, when: ansible_os_family == 'RedHat' }
